### ISSUE TITLE
Is it possible to use a binary cling build directly, without building it from source?

### ISSUE THREAD

**Issue by glyh** [jank-lang/jank#34]
As title, thanks.

**Comment by jeaye** [comment]
The cling sources are required, since jank needs to link with them. Just installing a cling binary using your package manager isn't going to get you the necessary libs for cling, clang, and llvm which jank needs to build. However, there is a ticket here for more pre-built binaries: https://github.com/jank-lang/jank/issues/26

You might also try the pre-built ubuntu binaries (even if you just run it in a docker container): https://github.com/jank-lang/jank/releases/tag/latest
